#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun May 04 00:10:48 CEST 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 7f4c3fa8d60b4aecb7b8d6765d859e37 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot CBadder_Nb_behav xil_defaultlib.CBadder_Nb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 7f4c3fa8d60b4aecb7b8d6765d859e37 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot CBadder_Nb_behav xil_defaultlib.CBadder_Nb xil_defaultlib.glbl -log elaborate.log

