#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat May 03 23:37:00 CEST 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim cla_adder_Nb_TB_behav -key {Behavioral:sim_1:Functional:cla_adder_Nb_TB} -tclbatch cla_adder_Nb_TB.tcl -log simulate.log"
xsim cla_adder_Nb_TB_behav -key {Behavioral:sim_1:Functional:cla_adder_Nb_TB} -tclbatch cla_adder_Nb_TB.tcl -log simulate.log

